app = "next-meeting-regenerate-schedule"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  RUN_INTERVAL_MINUTES = "60"

[[vm]]
  size = "shared-cpu-1x"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
